### ISSUE TITLE
potty racers 3 and 4 are both missing action scrip 3

### ISSUE THREAD

**Issue by solanaea** [lioxryt/lioxryt.github.io#13]

**Comment by lioxryt** [comment]
There isn't anything i could do right now but if a fix is to release i will fix them

**Comment by solanaea** [comment]
can you also add a game called road of the dead 2 and 1

**Comment by kurbus** [comment]
this is an inherent problem with the emulator itself (site uses ruffle i imagine, doesnt support as2 atm)

**Comment by lioxryt** [comment]
AS3 now supported
