### ISSUE TITLE
Can you add this to your page please

### ISSUE THREAD

**Issue by That1Marshmellow** [lioxryt/lioxryt.github.io#20]
I made it myself https://sites.google.com/view/rustybeanieman/home

**Comment by kurbus** [comment]
like, merge the games you have into our list? it could be possible

**Comment by That1Marshmellow** [comment]
Yeah like that

**Comment by lioxryt** [comment]
idk if im looking to add downloadable games at least for now

**Comment by That1Marshmellow** [comment]
Oh ok :( it's because at my sch we use Windows 10 and 11 desktops for work and to play .exe file games

**Comment by kurbus** [comment]
> Oh ok :( it's because at my sch we use Windows 10 and 11 desktops for work and to play .exe file games

my school has some windows laptops for students, however all of them have user level perms so even if we did include these they wouldn't run
