### ISSUE TITLE
other websites

### ISSUE THREAD

**Issue by DripyDude78** [lioxryt/lioxryt.github.io#23]
can you make the same website several times because it got blocked for me

**Comment by itschasa** [comment]
@DripyDude78 try using https://noblo.cc/
its an unblocked (hopefully) proxy, and shouldnt be detected automatically by filters at schools and workplaces

**Comment by lukemattle** [comment]
Damn https://noblo.cc is pretty good
I wonder who owns it :D

**Comment by joalricha869** [comment]
its blocked for me lol (using carbon black cloud and lightspeed systems relay btw)

**Comment by itschasa** [comment]
> its blocked for me lol (using carbon black cloud and lightspeed systems relay btw)

try:
noblocc.co
noblocc.co.uk

**Comment by joalricha869** [comment]
1. noblocc.co doesn't exist (error 404)
2. noblocc.co.uk is blocked as well lol

**Comment by lukemattle** [comment]
chasa means noblocc.uk instead of noblocc.co but yes there are multiple domains

**Comment by itschasa** [comment]
> 1. noblocc.co doesn't exist (error 404)
> 
> 2. noblocc.co.uk is blocked as well lol

did the site get auto-scanned by your filter?

**Comment by lukemattle** [comment]
we won't add measures to make our site unblockable by other schools with different blockers because we don't really have the time or the information required for us to achieve this
you can always check the discord for new domains though

**Comment by joalricha869** [comment]
its just blocked
![idiot](https://user-images.githubusercontent.com/83835381/221033108-79771a83-4e67-4ec4-bc1e-c800981574b8.JPG)

**Comment by joalricha869** [comment]
it think is auto scanned lol idk

**Comment by lukemattle** [comment]
We should probably leave this GitHub repo alone lmao
If you want to discuss further join the discord linked on the home page

**Comment by itschasa** [comment]
@joalricha869 https://discord.gg/uGa55xht
