### ISSUE TITLE
forked liox, just questions.

### ISSUE THREAD

**Issue by xefoolol** [lioxryt/lioxryt.github.io#26]
so everything's fine I got a website up and everything of my own, however whenever I press start playing it says "There isn't a GitHub Pages site here." Very confused I seeked to do this cause I was playing minecraft on yours, changed my render distance and I was stuck in a blank world for two minutes. After that I got tired of it and save and quit to main title screen and the saving world took forever but it was a fresh world, so I didn't mind if anything wasn't saved, killed task. Then I got a white screen when I pressed single player talking about crash detected so I refreshed and now your entire site won't work I decided I'd fork it and make my own as a workaround. Any help on either issue? 
![Screenshot 2023-01-18 1 28 08 AM](https://user-images.githubusercontent.com/122957572/213100299-933f50a9-6d2a-4582-812f-81e8971a2013.png)
![Screenshot 2023-01-18 1 28 01 AM](https://user-images.githubusercontent.com/122957572/213100323-4f7bab14-7e80-4172-8059-490b6a04d2f7.png)

**Comment by lioxryt** [comment]
For my site not working your school might have blocked it because it's getting big enough that schools are finding out about it now. For the error after forking my website isn't really the best coded so when u Forked it and named it whatever you have to go to the source code and change any redirect to have that name u set before it

**Comment by lioxryt** [comment]
Instead of making it go to https://xefoolol.github.io/html/main.html make it https://xefoolol.github.io/ET/html/main.html

**Comment by lioxryt** [comment]
This as also true for the css files not working
