### ISSUE TITLE
When I fork this and do all the steps and I click start playing it doesnt work and load the game section? How can I fix this?

### ISSUE THREAD

**Issue by ThinkXY** [lioxryt/lioxryt.github.io#29]

**Comment by lioxryt** [comment]
please link your fork

**Comment by lioxryt** [comment]
most common problem is that my code is bad and the redirects redirect to the root of the website and since your repo isn't titled YOURUSERNAME.github.io and its homepage isn't YOURUSERNAME.github.io its redirecting to a dead page

**Comment by ThinkXY** [comment]
https://github.com/ThinkXY/lioxryt.github.io

**Comment by ThinkXY** [comment]
how can I fix this?

**Comment by ThinkXY** [comment]
Your site was banned at my school so I'm trying to make another or something like that. I wish coding was easier.

**Comment by lioxryt** [comment]
Change your repos name to ThinkXY.github.io

**Comment by ThinkXY** [comment]
K did that

**Comment by ThinkXY** [comment]
is that all I have to do?

**Comment by ThinkXY** [comment]
Thank you it worked
