### ISSUE TITLE
Why does the site that I forked not work? It has my name in the thingy and it just fails in the end.

### ISSUE THREAD

**Issue by thinkbotyt** [lioxryt/lioxryt.github.io#32]
link is here. Please help https://github.com/thinkbotyt/thinkbotyt.github.io

**Comment by ThinkXY** [comment]
I actually got the exact same issue with mine. I tried to update the commit because I know you made some changes, but it kept failing as well.

**Comment by lioxryt** [comment]
Bro I'm ngl idk it's failing for me too

**Comment by thinkbotyt** [comment]
maybe they dont support the old way. Maybe you have to use Github actions

**Comment by lioxryt** [comment]
Yea I saw so it's not a coding error cuz the main and backup are the exact same
