### ISSUE TITLE
Link back to Sandboxels

### ISSUE THREAD

**Issue by slweeb** [lioxryt/lioxryt.github.io#39]
I'm the developer of Sandboxels. Happy to let you include it in your thing, but please add a link back to it on its page. An "Official Website" link going to https://sandboxels.r74n.com/.

**Comment by lioxryt** [comment]
Yes of course no problem I am in class rn but will do when I get home 

Also thanks for letting me include it

Do you want me to link anything else

**Comment by slweeb** [comment]
That's all! Thanks

**Comment by lioxryt** [comment]
ok i made the change and i am deploying the edit

Thanks again for letting me use it
