### ISSUE TITLE
Proxy2 does not work

### ISSUE THREAD

**Issue by ghost** [lioxryt/lioxryt.github.io#4]

**Comment by lio2xr** [comment]
Damn there was so much traffic you guys shut it down

**Comment by Rustycomeback** [comment]
What do you mean by traffic?

**Comment by lio2xr** [comment]
There was a lot of users accessing it

**Comment by Rustycomeback** [comment]
And can you fix it by using codebox?

**Comment by lioxryt** [comment]
forgot all about the proxies fr
