### ISSUE TITLE
Games not loading

### ISSUE THREAD

**Issue by feeshmaster** [lioxryt/lioxryt.github.io#41]
When i open a game it just pops something up which doesn’t do anything.

**Comment by lioxryt** [comment]
Yea we just implemented a new game loading system and it is not done please mess around with the cdn settings but no promises it will work as it is not done

**Comment by giggist** [comment]
Yeah, all it says is that the site is blocked or sends me to a 404 error. The first two are blocked and the last is an error.

**Comment by lioxryt** [comment]
it should be fixed now so give it a try github is still having deployment issues though
