### ISSUE TITLE
Discord & 1 game not working

### ISSUE THREAD

**Issue by Sum0001** [lioxryt/lioxryt.github.io#44]
### Name

Sum1

### Review

Tactical Weapon Pack 2 won't load, oh & the built-in Discord isn't working either.

### Profile picture

?

**Comment by lioxryt** [comment]
The discord has been turned of since there was too many slurs and tactical weapons pack 2 will be fixed thanks for letting me know

**Comment by Sum0001** [comment]
Never mind, tactical weapons pack 2 doesn't work, I think the problem is within the game itself

**Comment by lioxryt** [comment]
are you on lioxryt or lioxrytbackup
