### ISSUE TITLE
For the lioxryt's Discord its asking for your REAL discord and opening a new page of chrome

### ISSUE THREAD

**Issue by That1Marshmellow** [lioxryt/lioxryt.github.io#48]
can you fix that?

**Comment by lioxryt** [comment]
yea unfortunately we hade to turn of the guest mode as people were sending not so good things

**Comment by That1Marshmellow** [comment]
Oh before you turned off guest mode I saw images of weird stuff

**Comment by lioxryt** [comment]
people racist/weird = no guestmode
