### ISSUE TITLE
New Proxy pls add

### ISSUE THREAD

**Issue by Rustycomeback** [lioxryt/lioxryt.github.io#7]
https://google0workspace.up.railway.app/

**Comment by lioxryt** [comment]
both your proxies say not found

**Comment by Rustycomeback** [comment]
https://that1marshmellow.up.railway.app/

**Comment by Rustycomeback** [comment]
https://thegoogleworkspace.up.railway.app/

**Comment by Rustycomeback** [comment]
I did them myself
check out my GitHub page That1Marshmellow

**Comment by lioxryt** [comment]
the links lead to a dead page
